(function(){
 const here=location.pathname.split('/').pop()||'index.html';
 const nav=[['index.html','Accueil'],['index.html#espaces','Espaces'],['formations.html','Formations'],['galerie.html','Galerie'],['a-propos.html','Qui sommes-nous']];
 document.getElementById('hdr').innerHTML='<header class="top" id="top-h"><a class="logo" href="index.html"><img src="'+PH.logo+'" alt="Initiative Academy" onerror="this.replaceWith(Object.assign(document.createElement(\'b\'),{textContent:\'INITIATIVE ACADEMY\'}))"></a><nav>'+nav.map(n=>'<a href="'+n[0]+'"'+(n[0]===here?' class="act"':'')+'>'+n[1]+'</a>').join('')+'</nav><div class="hr"><a class="tel" href="tel:'+CO.telh+'">'+CO.tel+'</a><a class="cta" href="rendez-vous.html">Prendre rendez-vous</a><button class="burger" type="button" aria-label="Menu"><i></i><i></i></button></div></header><div class="menu" id="menu"><button class="mx" type="button" aria-label="Fermer">✕</button>'+nav.concat([['rendez-vous.html','Prendre rendez-vous']]).map(n=>'<a href="'+n[0]+'">'+n[1]+'</a>').join('')+'<p><a href="tel:'+CO.telh+'">'+CO.tel+'</a></p></div>';
 const f=document.getElementById('ftr');if(f)f.innerHTML='<footer class="ft"><div class="wrap fg"><div><img src="'+PH.logo+'" alt="Initiative Academy" class="flogo"><p>Un hub professionnel complet au cœur d\'Alger, conçu pour accompagner les entrepreneurs et les entreprises dans leur développement.</p><div class="soc"><a href="'+CO.fb+'" target="_blank" rel="noopener">Facebook</a><a href="'+CO.ig+'" target="_blank" rel="noopener">Instagram</a><a href="'+CO.li+'" target="_blank" rel="noopener">LinkedIn</a></div></div><div><h4>Services</h4>'+SERV.map(s=>'<a href="index.html#'+s[0]+'">'+s[1]+'</a>').join('')+'</div><div><h4>Contact</h4><p>'+CO.adr+'</p><a href="tel:'+CO.telh+'">'+CO.tel+'</a><a href="mailto:'+CO.mail+'">'+CO.mail+'</a></div><div><h4>Horaires</h4><p>Lun — Ven : 08 h — 20 h<br>Sam — Dim : sur rendez-vous</p><a class="cta sm" href="rendez-vous.html">Prendre rendez-vous</a></div></div><div class="wrap fb"><span>© 2026 Initiative Academy. Tous droits réservés.</span><span>Maquette réalisée par Webminds</span></div></footer>';
 const isV2=here==='corporate.html';if(here==='index.html'||isV2){try{localStorage.setItem('ia_home',here)}catch(e){}}
 let home='index.html';try{home=localStorage.getItem('ia_home')||'index.html'}catch(e){}
 const toV2=(here==='index.html')||(!isV2&&home!=='corporate.html');
 const sw=document.createElement('a');sw.className='vswitch';sw.href=toV2?'corporate.html':'index.html';sw.innerHTML=toV2?'<span class="vs-i">◆</span><span><small>Découvrir la</small>Version Corporate</span>':'<span class="vs-i">✦</span><span><small>Revenir à la</small>Version Élégance</span>';document.body.appendChild(sw);
 document.querySelectorAll('a[href="index.html"]').forEach(a=>{if(home==='corporate.html'&&!a.closest('.vswitch'))a.href='corporate.html'});
 const b=document.createElement('div');b.id='wm-demo';b.textContent='Maquette de démonstration réalisée par Webminds · aucun formulaire n\'est enregistré';document.body.appendChild(b);
 const m=document.getElementById('menu');document.addEventListener('click',e=>{if(e.target.closest('.burger'))m.classList.add('open');if(e.target.closest('.mx')||e.target.closest('.menu a'))m.classList.remove('open')});
 const th=document.getElementById('top-h');const s=()=>th.classList.toggle('solid',scrollY>40);addEventListener('scroll',s,{passive:true});s();
 const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.1});
 window.reveal=()=>document.querySelectorAll('.rv:not([data-o])').forEach(e=>{e.dataset.o=1;io.observe(e)});reveal();
})();
function okForm(f,msg){const b=f.querySelector('button[type=submit]'),t=b.textContent;b.textContent=msg;b.disabled=true;b.classList.add('done');setTimeout(()=>{f.reset();b.textContent=t;b.disabled=false;b.classList.remove('done')},3500)}
const ICO={wifi:'<path d="M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M2 9a15 15 0 0 1 20 0"/><circle cx="12" cy="19.5" r="1"/>',print:'<path d="M6 9V3h12v6M6 18H4v-6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v6h-2M6 14h12v7H6z"/>',sofa:'<path d="M4 11V8a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v3M2 13a2 2 0 0 1 4 0v2h12v-2a2 2 0 0 1 4 0v5H2zM5 18v2M19 18v2"/>',room:'<path d="M3 21h18M5 21V5h14v16M9 9h6M9 13h6"/>',cup:'<path d="M4 8h13v5a6 6 0 0 1-6 6h-1a6 6 0 0 1-6-6zM17 9h1.5a2.5 2.5 0 0 1 0 5H17M8 2v3M12 2v3"/>',lock:'<rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>'};
const icon=k=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+ICO[k]+'</svg>';
