(function(){
 const here=location.pathname.split('/').pop()||'index.html';
 const here2=here+location.search;
 const nav=[['index.html','Accueil'],['dd','Services'],['formations.html','Formations'],['galerie.html','Galerie'],['a-propos.html','Qui sommes-nous'],['salon.html','Salon FormaTech']];
 const SUB=[['Entreprises',['creation','domiciliation','boite','assistance']],['Espaces',['coworking','incubateur','bureaux','salles']]];
 const dd='<div class="dd"><button type="button" class="ddb'+(here==='service.html'?' act':'')+'">Services <span>▾</span></button><div class="ddm">'+SUB.map(g=>'<div><small>'+g[0]+'</small>'+g[1].map(s=>'<a href="service.html?s='+s+'"'+(here2==='service.html?s='+s?' class="act"':'')+'>'+SD[s].t+'</a>').join('')+'</div>').join('')+'<div><small>Formations</small><a href="formations.html">Catalogue des formations</a><a href="rendez-vous.html">Prendre rendez-vous</a></div></div></div>';
 document.getElementById('hdr').innerHTML='<header class="top" id="top-h"><a class="logo" href="index.html"><img src="img/'+(document.body.classList.contains('v2')?'logo-color':'logo-light')+'.png" alt="Initiative Academy" onerror="this.replaceWith(Object.assign(document.createElement(\'b\'),{textContent:\'INITIATIVE ACADEMY\'}))"></a><nav>'+nav.map(n=>n[0]==='dd'?dd:'<a href="'+n[0]+'"'+(n[0]===here?' class="act"':'')+'>'+n[1]+'</a>').join('')+'</nav><div class="hr"><a class="tel" href="tel:'+CO.telh+'">'+CO.tel+'</a><a class="cta" href="rendez-vous.html">Prendre rendez-vous</a><button class="burger" type="button" aria-label="Menu"><i></i><i></i></button></div></header><div class="menu" id="menu"><button class="mx" type="button" aria-label="Fermer">✕</button><a href="index.html">Accueil</a>'+SUB.map(g=>'<small>'+g[0]+'</small>'+g[1].map(s=>'<a class="sm" href="service.html?s='+s+'">'+SD[s].t+'</a>').join('')).join('')+'<small>Plus</small><a class="sm" href="formations.html">Formations</a><a class="sm" href="galerie.html">Galerie</a><a class="sm" href="a-propos.html">Qui sommes-nous</a><a class="sm" href="salon.html">Salon FormaTech · 12–15 oct</a><a class="sm" href="rendez-vous.html">Prendre rendez-vous</a><p><a href="tel:'+CO.telh+'">'+CO.tel+'</a></p></div>';
 document.addEventListener('click',e=>{const b=e.target.closest('.ddb');document.querySelectorAll('.dd').forEach(d=>d.classList.toggle('open',!!b&&d.contains(b)&&!d.classList.contains('open')))});
 const MQ=encodeURIComponent('Initiative Academy, Saïd Hamdine, Alger');
 const mp=document.createElement('section');mp.className='mapw';mp.innerHTML='<div class="wrap"><div class="map"><div class="mi"><span class="kick">Nous trouver</span><h2 style="font-size:clamp(28px,3vw,40px)">Initiative Academy</h2><p style="color:var(--mut)">'+CO.adr+'<br>Dim — Jeu : 08 h — 16 h<br>Ven — Sam : sur rendez-vous</p><p><a href="tel:'+CO.telh+'" style="font-weight:700">☎ '+CO.tel+'</a><br><a href="mailto:'+CO.mail+'">'+CO.mail+'</a></p><div style="display:flex;gap:10px;flex-wrap:wrap"><a class="btn b" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query='+MQ+'">Itinéraire Google Maps</a><a class="btn o" href="rendez-vous.html">Prendre rendez-vous</a></div></div><iframe title="Carte Google Maps Initiative Academy" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://www.google.com/maps?q='+MQ+'&output=embed"></iframe></div></div>';
 if(here!=='salon.html'&&!/v[45]\.html/.test(here)&&Date.now()<Date.parse('2026-10-16T00:00:00+01:00')){const sp=document.createElement('a');sp.href='salon.html';sp.id='sx-pill';sp.innerHTML='<i></i><span><b>FormaTech Expo</b> · 12–15 oct · SAFEX Pavillon A</span><em>→</em>';document.body.appendChild(sp)}
 const mn=document.querySelector('main');if(mn)mn.appendChild(mp);
 const f=document.getElementById('ftr');if(f)f.innerHTML='<footer class="ft"><div class="wrap fg"><div><img src="'+'img/logo-light.png'+'" alt="Initiative Academy" class="flogo"><p>Un hub professionnel complet au cœur d\'Alger, conçu pour accompagner les entrepreneurs et les entreprises dans leur développement.</p><div class="soc"><a href="'+CO.fb+'" target="_blank" rel="noopener">Facebook</a><a href="'+CO.ig+'" target="_blank" rel="noopener">Instagram</a><a href="'+CO.li+'" target="_blank" rel="noopener">LinkedIn</a></div></div><div><h4>Services</h4>'+SORDER.map(s=>'<a href="service.html?s='+s+'">'+SD[s].t+'</a>').join('')+'<a href="formations.html">Formations</a></div><div><h4>Contact</h4><p>'+CO.adr+'</p><a href="tel:'+CO.telh+'">'+CO.tel+'</a><a href="mailto:'+CO.mail+'">'+CO.mail+'</a></div><div><h4>Horaires</h4><p>Dim — Jeu : 08 h — 16 h<br>Ven — Sam : sur rendez-vous</p><a class="cta sm" href="rendez-vous.html">Prendre rendez-vous</a></div></div><div class="wrap fb"><span>© 2026 Initiative Academy. Tous droits réservés.</span><span>Site réalisé par Webminds</span></div></footer>';
 const VER=[['index.html','Élégance'],['corporate.html','Corporate'],['v4.html','Le Film'],['v5.html','Le Scénario']];
 if(VER.some(v=>v[0]===here)){try{localStorage.setItem('ia_home',here)}catch(e){}}
 let home='index.html';try{home=localStorage.getItem('ia_home')||'index.html'}catch(e){}if(!VER.some(v=>v[0]===home))home='index.html';
 const cur=VER.find(v=>v[0]===here)||VER.find(v=>v[0]===home)||VER[0];
 const sw=document.createElement('div');sw.className='vswitch-w';sw.innerHTML='<div class="vmenu">'+VER.map(v=>'<a href="'+v[0]+'"'+(v[0]===cur[0]?' class="on"':'')+'>Version '+v[1]+'</a>').join('')+'</div><button type="button" class="vswitch"><span class="vs-i">◆</span><span><small>Découvrir les</small>4 versions du site</span></button>';document.body.appendChild(sw);
 sw.querySelector('.vswitch').addEventListener('click',()=>sw.classList.toggle('open'));
 document.querySelectorAll('a[href="index.html"]').forEach(a=>{if(home!=='index.html'&&!a.closest('.vswitch-w'))a.href=home});
 const m=document.getElementById('menu');document.addEventListener('click',e=>{if(e.target.closest('.burger'))m.classList.add('open');if(e.target.closest('.mx')||e.target.closest('.menu a'))m.classList.remove('open')});
 const th=document.getElementById('top-h');const s=()=>th.classList.toggle('solid',scrollY>40);addEventListener('scroll',s,{passive:true});s();
 const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');io.unobserve(x.target)}}),{threshold:.1});
 window.reveal=()=>document.querySelectorAll('.rv:not([data-o])').forEach(e=>{e.dataset.o=1;io.observe(e)});reveal();
})();
const FORM_TO='https://formsubmit.co/ajax/'+(window.CO?CO.mail:'contact@initiativeacademy.dz');
function formData(f){const o={};f.querySelectorAll('input,select,textarea').forEach(el=>{if(el.type==='submit'||el.type==='button')return;if((el.type==='radio'||el.type==='checkbox')&&!el.checked)return;let k=el.name&&!['sv','sl'].includes(el.name)?el.name:'';if(el.name==='sv')k='Service souhaité';if(el.name==='sl')k='Créneau';if(!k){const l=el.closest('label');k=l?[...l.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent).join(' ').trim():'Champ'}if(!k)k='Champ';const v=(el.value||'').trim();if(!v)return;o[k]=o[k]?o[k]+', '+v:v});return o}
function okForm(f,msg,subj){const b=f.querySelector('button[type=submit]'),t=b.textContent;const data=formData(f);data._subject=(subj||'Nouvelle demande')+' — site initiativeacademy.dz'+(data['Formation']?' : '+data['Formation']:data['Service']?' : '+data['Service']:'');data._template='table';data._captcha='false';data['Page']=location.href;const em=data['E-mail'];if(em)data._replyto=em;
b.textContent='Envoi en cours…';b.disabled=true;
fetch(FORM_TO,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(data)}).then(r=>r.json()).then(j=>{if(j.success===false||j.success==='false')throw 0;b.textContent=msg;b.classList.add('done');setTimeout(()=>{f.reset();b.textContent=t;b.disabled=false;b.classList.remove('done')},4000)}).catch(()=>{b.textContent='Échec de l\'envoi — appelez le '+CO.tel;setTimeout(()=>{b.textContent=t;b.disabled=false},5000)})}
const ICO={wifi:'<path d="M5 12.5a10 10 0 0 1 14 0M8.5 16a5 5 0 0 1 7 0M2 9a15 15 0 0 1 20 0"/><circle cx="12" cy="19.5" r="1"/>',print:'<path d="M6 9V3h12v6M6 18H4v-6a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v6h-2M6 14h12v7H6z"/>',sofa:'<path d="M4 11V8a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v3M2 13a2 2 0 0 1 4 0v2h12v-2a2 2 0 0 1 4 0v5H2zM5 18v2M19 18v2"/>',room:'<path d="M3 21h18M5 21V5h14v16M9 9h6M9 13h6"/>',cup:'<path d="M4 8h13v5a6 6 0 0 1-6 6h-1a6 6 0 0 1-6-6zM17 9h1.5a2.5 2.5 0 0 1 0 5H17M8 2v3M12 2v3"/>',lock:'<rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>'};
const icon=k=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">'+ICO[k]+'</svg>';
