/* Sons de synthèse (aucun fichier audio) : explosion, tonnerre, montée d'énergie, souffle */
const SFX=(function(){let ctx=null,on=false,master;
 function init(){if(ctx)return;ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.gain.value=.55;master.connect(ctx.destination)}
 function noise(d){const b=ctx.createBuffer(1,ctx.sampleRate*d,ctx.sampleRate),c=b.getChannelData(0);for(let i=0;i<c.length;i++)c[i]=Math.random()*2-1;const s=ctx.createBufferSource();s.buffer=b;return s}
 function env(node,t,a,peak,dec){node.gain.setValueAtTime(0,t);node.gain.linearRampToValueAtTime(peak,t+a);node.gain.exponentialRampToValueAtTime(.0001,t+a+dec)}
 return{_ctx:()=>ctx,_out:()=>master,enable(){init();on=true;ctx.resume()},disable(){on=false},get on(){return on},
  boom(p=1){if(!on)return;const t=ctx.currentTime;const n=noise(3),f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.setValueAtTime(1800,t);f.frequency.exponentialRampToValueAtTime(90,t+2.2);const g=ctx.createGain();env(g,t,.01,1*p,2.6);n.connect(f).connect(g).connect(master);n.start(t);
   const o=ctx.createOscillator();o.type='sine';o.frequency.setValueAtTime(90,t);o.frequency.exponentialRampToValueAtTime(28,t+1.6);const g2=ctx.createGain();env(g2,t,.01,1.2*p,1.8);o.connect(g2).connect(master);o.start(t);o.stop(t+2)},
  thunder(){if(!on)return;const t=ctx.currentTime;const n=noise(2.5),f=ctx.createBiquadFilter();f.type='bandpass';f.frequency.value=1200;f.Q.value=.6;const g=ctx.createGain();g.gain.setValueAtTime(0,t);
   for(let i=0;i<5;i++){g.gain.linearRampToValueAtTime(.6*Math.random()+.2,t+i*.06+.01);g.gain.linearRampToValueAtTime(.05,t+i*.06+.05)}g.gain.exponentialRampToValueAtTime(.0001,t+2.2);n.connect(f).connect(g).connect(master);n.start(t)},
  rise(d=1.4){if(!on)return;const t=ctx.currentTime,o=ctx.createOscillator(),o2=ctx.createOscillator(),g=ctx.createGain();o.type='sawtooth';o2.type='sine';o.frequency.setValueAtTime(60,t);o.frequency.exponentialRampToValueAtTime(900,t+d);o2.frequency.setValueAtTime(40,t);o2.frequency.exponentialRampToValueAtTime(320,t+d);
   const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.setValueAtTime(300,t);f.frequency.exponentialRampToValueAtTime(5000,t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.35,t+d);g.gain.linearRampToValueAtTime(0,t+d+.05);o.connect(f);o2.connect(f);f.connect(g).connect(master);o.start(t);o2.start(t);o.stop(t+d+.1);o2.stop(t+d+.1)},
  whoosh(){if(!on)return;const t=ctx.currentTime,n=noise(.8),f=ctx.createBiquadFilter();f.type='bandpass';f.Q.value=1.2;f.frequency.setValueAtTime(300,t);f.frequency.exponentialRampToValueAtTime(3000,t+.35);f.frequency.exponentialRampToValueAtTime(400,t+.7);const g=ctx.createGain();env(g,t,.2,.35,.5);n.connect(f).connect(g).connect(master);n.start(t)},
  hum(){if(!on)return;const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.value=55;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.06,t+2);o.connect(g).connect(master);o.start(t);return()=>{g.gain.linearRampToValueAtTime(0,ctx.currentTime+.5);o.stop(ctx.currentTime+.6)}}}})();
/* Musique d'ambiance de synthèse : nappes + pulsation, 3 ambiances */
SFX.music=(function(){let nodes=null,mood='calm',beat=null;
 const CH={calm:[[110,138.6,164.8],[98,123.5,146.8]],tension:[[103.8,123.5,155.6],[98,116.5,146.8]],epic:[[110,164.8,220,277.2],[130.8,196,261.6,329.6]]};
 function start(){if(nodes||!SFX.on)return;const ctx=SFX._ctx();const out=ctx.createGain();out.gain.value=0;out.connect(SFX._out());out.gain.linearRampToValueAtTime(.16,ctx.currentTime+3);
  const f=ctx.createBiquadFilter();f.type='lowpass';f.frequency.value=900;f.Q.value=.8;f.connect(out);
  const osc=[];for(let i=0;i<4;i++){const o=ctx.createOscillator(),o2=ctx.createOscillator(),g=ctx.createGain();o.type='sawtooth';o2.type='sawtooth';o2.detune.value=9;g.gain.value=.1;o.connect(g);o2.connect(g);g.connect(f);o.start();o2.start();osc.push([o,o2,g])}
  nodes={out,f,osc};set(mood,true);let i=0;beat=setInterval(()=>{if(!nodes)return;const c=CH[mood][i%CH[mood].length];i++;nodes.osc.forEach((v,k)=>{const fr=c[k%c.length]*(k>=c.length?2:1);v[0].frequency.linearRampToValueAtTime(fr,ctx.currentTime+1.5);v[1].frequency.linearRampToValueAtTime(fr,ctx.currentTime+1.5)});if(mood!=='calm')pulse(mood==='epic'?1:.6)},mood==='tension'?2000:4000)}
 function pulse(p){const ctx=SFX._ctx(),t=ctx.currentTime;[0,.32].forEach(d=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(70,t+d);o.frequency.exponentialRampToValueAtTime(38,t+d+.25);g.gain.setValueAtTime(0,t+d);g.gain.linearRampToValueAtTime(.5*p,t+d+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d+.3);o.connect(g).connect(SFX._out());o.start(t+d);o.stop(t+d+.35)})}
 function set(m,now){mood=m;if(!nodes)return;const ctx=SFX._ctx();nodes.f.frequency.linearRampToValueAtTime(m==='epic'?2600:m==='tension'?1300:800,ctx.currentTime+(now?0:2));nodes.out.gain.linearRampToValueAtTime(m==='epic'?.22:m==='tension'?.17:.13,ctx.currentTime+2)}
 function stop(){if(!nodes)return;const ctx=SFX._ctx(),n=nodes;nodes=null;clearInterval(beat);n.out.gain.linearRampToValueAtTime(0,ctx.currentTime+2);setTimeout(()=>n.osc.forEach(v=>{v[0].stop();v[1].stop()}),2200)}
 return{start,set,stop,pulse}})();
